version: "3.7"
services:
  postgres: 
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres

    ports:
      - "5432:5432"
    