version: "3.7"
services:
  postgres: 
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres

    ports:
      - "5432:5432"

  books-app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5433/Book
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"

        
    