version: "3.7"
services:
  postgres: 
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/pg_data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./db/2_init.sql:/docker-entrypoint-initdb.d/2_init.sql
    ports:
      - "5432:5432"

  books-app:
    build:
      context: .
    depends_on:
      postgres: 
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/
      NODE_ENV: $NODE_ENV
      PORT: 4000
      # EXTERNAL_PORT: 3001
      PGDATABASE: $PGDATABASE
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGHOST: $PGHOST
    ports:
      - "4000:4000"

volumes: 
  data: {}

    